INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_EMPLOYEE');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MANAGER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_HR');

